[theme]
base = "dark"

# Kolory bazowe w duchu Spotify
textColor = "#EDEDED"
primaryColor = "#1DB954"
backgroundColor = "#0B0B0B"
secondaryBackgroundColor = "#181818"

# Widżety
showWidgetBorder = true
borderColor = "#2A2A2A"
baseRadius = "0.9rem"

# Tabele danych
dataframeHeaderBackgroundColor = "#181818"

# Tekst bazowy
font = "'Montserrat':https://fonts.googleapis.com/css2?family=Montserrat:wght@300..800&display=swap"
baseFontWeight = 400
baseFontSize = 14

# Nagłówki
headingFont = "Montserrat"
headingFontWeights = [800, 700, 600, 600, 500, 500]
headingFontSizes = ["2.6rem", "1.6rem", "1.15rem"]
